version: 2.1

orbs:
  go: circleci/go@1.1.1
  codecov: codecov/codecov@1.0.5

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    executor:
      name: go/default
      tag: '1.13'
    steps:
      - checkout
      - go/test:
          coverprofile: coverage.out
          covermode: atomic
          failfast: true
          race: true
      - codecov/upload:
          file: coverage.out
