version: 2.1

orbs:
  go: circleci/go@1.1.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    executor:
      name: go/default
      tag: '1.13'
    steps:
      - checkout
      - go/test:
          covermode: atomic
          failfast: true
          race: true
